-- MySQL Script generated by MySQL Workbench
-- Fri Mar 31 16:06:12 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema compania
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema compania
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `compania` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `compania` ;

-- -----------------------------------------------------
-- Table `compania`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compania`.`departamento` (
  `dnombre` VARCHAR(30) NULL DEFAULT NULL,
  `dnumero` INT NOT NULL AUTO_INCREMENT,
  `jefeci` VARCHAR(10) NULL DEFAULT NULL,
  `jefe_fi` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`dnumero`),
  INDEX `jefeci` (`jefeci` ASC) VISIBLE,
  CONSTRAINT `departamento_ibfk_1`
    FOREIGN KEY (`jefeci`)
    REFERENCES `compania`.`empleado` (`ci`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `compania`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compania`.`empleado` (
  `nombre` VARCHAR(30) NULL DEFAULT NULL,
  `apellido` VARCHAR(30) NULL DEFAULT NULL,
  `ci` VARCHAR(10) NOT NULL,
  `fecha_n` DATE NULL DEFAULT NULL,
  `direccion` VARCHAR(30) NULL DEFAULT NULL,
  `sexo` CHAR(1) NULL DEFAULT NULL,
  `salario` INT NULL DEFAULT NULL,
  `superci` VARCHAR(10) NULL DEFAULT NULL,
  `dno` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ci`),
  INDEX `dno` (`dno` ASC) VISIBLE,
  INDEX `superci` (`superci` ASC) VISIBLE,
  CONSTRAINT `empleado_ibfk_1`
    FOREIGN KEY (`dno`)
    REFERENCES `compania`.`departamento` (`dnumero`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `empleado_ibfk_2`
    FOREIGN KEY (`superci`)
    REFERENCES `compania`.`empleado` (`ci`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `compania`.`carga_f`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compania`.`carga_f` (
  `eci` VARCHAR(10) NOT NULL,
  `dep_nom` VARCHAR(30) NULL DEFAULT NULL,
  `sexo` VARCHAR(1) NULL DEFAULT NULL,
  `fecha_n` DATE NULL DEFAULT NULL,
  `relacion` VARCHAR(10) NULL DEFAULT NULL,
  INDEX `eci` (`eci` ASC) VISIBLE,
  CONSTRAINT `carga_f_ibfk_1`
    FOREIGN KEY (`eci`)
    REFERENCES `compania`.`empleado` (`ci`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `compania`.`localizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compania`.`localizacion` (
  `dnumero` INT NOT NULL,
  `dep_loca` VARCHAR(30) NULL DEFAULT NULL,
  INDEX `dnumero` (`dnumero` ASC) VISIBLE,
  CONSTRAINT `localizacion_ibfk_1`
    FOREIGN KEY (`dnumero`)
    REFERENCES `compania`.`departamento` (`dnumero`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `compania`.`proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compania`.`proyecto` (
  `pnombre` VARCHAR(30) NULL DEFAULT NULL,
  `pnumero` INT NOT NULL AUTO_INCREMENT,
  `plocal` VARCHAR(30) NULL DEFAULT NULL,
  `dnum` INT NULL DEFAULT NULL,
  PRIMARY KEY (`pnumero`),
  INDEX `dnum` (`dnum` ASC) VISIBLE,
  CONSTRAINT `proyecto_ibfk_1`
    FOREIGN KEY (`dnum`)
    REFERENCES `compania`.`departamento` (`dnumero`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `compania`.`trabaja_en`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compania`.`trabaja_en` (
  `eci` VARCHAR(10) NOT NULL,
  `pno` INT NOT NULL,
  `horas` DOUBLE(4,2) NULL DEFAULT NULL,
  INDEX `eci` (`eci` ASC) VISIBLE,
  INDEX `pno` (`pno` ASC) VISIBLE,
  CONSTRAINT `trabaja_en_ibfk_1`
    FOREIGN KEY (`eci`)
    REFERENCES `compania`.`empleado` (`ci`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `trabaja_en_ibfk_2`
    FOREIGN KEY (`pno`)
    REFERENCES `compania`.`proyecto` (`pnumero`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
